version: 2

models:
  - name: fact_oil_supply
    description: "Bảng Fact tổng hợp nguồn cung dầu (Nhập khẩu và Khai thác nội địa)"
    columns:
      # Đổi tên cột từ supply_id thành source_id
      - name: source_id
        description: "Mã định danh duy nhất (MD5 Hash)"
        tests:
          - not_null
          
          
      - name: supply_source
        description: "Nguồn cung cấp dầu"
        tests:
          - accepted_values:
              # Đảm bảo viết chính xác từng chữ cái và dấu gạch dưới như trong file SQL
              values: ['Import', 'Domestic_Production']
              
      - name: supply_date
        description: "Ngày ghi nhận nguồn cung"
        tests:
          - not_null
          
      - name: volume_bbl
        description: "Khối lượng (Thùng)"
        tests:
          - not_null