# Tên dự án (Bắt buộc phải có)
name: 'oil_transformation'
version: '1.0.0'
config-version: 2

# Tên profile trỏ về file profiles.yml của bạn
profile: 'oil_transformation'

# Chỉ định các thư mục chứa code
model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

# Cấu hình mặc định cho các thư mục
models:
  oil_transformation:
    # Các model trong thư mục staging sẽ được tạo dưới dạng View
    staging:
      +materialized: view
    # Các model trong thư mục marts sẽ được tạo dưới dạng Table (vật lý)
    marts:
      +materialized: table