oil_transformation:
  target: dev
  outputs:
    dev:
      type: duckdb
      # Đường dẫn trỏ thẳng vào file database do dlt vừa tạo ra
      path: '../data_lake/processed/zoomcamp_dw.duckdb'
      # Kích hoạt tính năng đọc file Parquet
      extensions:
        - parquet